version: '3'
app:
  build: .
  environment:
    - INSERTION_QUEUE: insertion.queue
  links:
    - mysql:mysql
    - rabbitmq:rabbitmq
mysql:
  image: mysql:5.7
  environment:
    MYSQL_DATABASE: axr_challenge
    MYSQL_ROOT_PASSWORD: secret
  ports:
    - 3306:3306
rabbitmq:
  image: rabbitmq:3.6-management
  ports:
    - 5672:5672
    - 15672:15672
